# Generated by Django 5.2.7 on 2025-10-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, help_text='Overall profile score (0-100)', verbose_name='Overall Profile Score')),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, help_text='Profile completion percentage (0-100)', verbose_name='Profile Completion Percentage')),
                ('last_boosted_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Boosted At')),
                ('boost_count', models.PositiveIntegerField(default=0, help_text='Number of times profile has been boosted', verbose_name='Boost Count')),
                ('personal_info_score', models.PositiveSmallIntegerField(default=0, verbose_name='Personal Info Score')),
                ('experience_score', models.PositiveSmallIntegerField(default=0, verbose_name='Experience Score')),
                ('education_score', models.PositiveSmallIntegerField(default=0, verbose_name='Education Score')),
                ('skills_score', models.PositiveSmallIntegerField(default=0, verbose_name='Skills Score')),
                ('certifications_score', models.PositiveSmallIntegerField(default=0, verbose_name='Certifications Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booster_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booster Progress',
                'verbose_name_plural': 'Booster Progress',
            },
        ),
        migrations.CreateModel(
            name='ProfileBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_type', models.CharField(choices=[('profile_completion', 'Profile Completion'), ('skill_improvement', 'Skill Improvement'), ('experience_enhancement', 'Experience Enhancement'), ('education_boost', 'Education Boost'), ('certification_addition', 'Certification Addition')], default='profile_completion', max_length=50, verbose_name='Booster Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('score_before', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score Before')),
                ('score_after', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score After')),
                ('improvement_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Improvement Percentage')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations for improvement', verbose_name='Recommendations')),
                ('applied_changes', models.JSONField(default=list, help_text='List of changes applied to the profile', verbose_name='Applied Changes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_boosters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile Booster',
                'verbose_name_plural': 'Profile Boosters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoosterRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skills', 'Skills'), ('experience', 'Experience'), ('education', 'Education'), ('certification', 'Certification'), ('personal_info', 'Personal Information'), ('summary', 'Professional Summary')], default='skills', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the recommendation', verbose_name='Description')),
                ('action_text', models.CharField(help_text='Text for the action button', max_length=255, verbose_name='Action Text')),
                ('action_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Action URL')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_recommendations', to='profile_booster.profilebooster', verbose_name='Profile Booster')),
            ],
            options={
                'verbose_name': 'Booster Recommendation',
                'verbose_name_plural': 'Booster Recommendations',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
