# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('matching', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateembedding',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='users.candidateprofile'),
        ),
        migrations.AddField(
            model_name='jobembedding',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='users.candidateprofile'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='matchscore',
            unique_together={('candidate', 'job')},
        ),
    ]
