# Generated by Django 5.2.7 on 2025-10-03 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCheckSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Setting Name')),
                ('value', models.JSONField(help_text='JSON-encoded setting value', verbose_name='Setting Value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Resume Check Setting',
                'verbose_name_plural': 'Resume Check Settings',
            },
        ),
        migrations.CreateModel(
            name='ResumeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(max_length=500, upload_to='resume_checks/%Y/%m/%d/', verbose_name='Resume File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(help_text='Size of the uploaded file in bytes', verbose_name='File Size (bytes)')),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, help_text='Overall resume score (0-100)', null=True, verbose_name='Overall Score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('analysis', models.JSONField(default=dict, help_text='Detailed analysis results in JSON format', verbose_name='Analysis Results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_checker_checks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume Check',
                'verbose_name_plural': 'Resume Checks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResumeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('content', 'Content'), ('format', 'Format'), ('style', 'Style'), ('grammar', 'Grammar'), ('length', 'Length'), ('other', 'Other')], default='other', max_length=20, verbose_name='Issue Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the issue', verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='Where in the resume this issue was found', max_length=100, null=True, verbose_name='Location')),
                ('suggestion', models.TextField(blank=True, help_text='Suggested improvement', null=True, verbose_name='Suggestion')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resume_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='resume_checker.resumecheck', verbose_name='Resume Check')),
            ],
            options={
                'verbose_name': 'Resume Issue',
                'verbose_name_plural': 'Resume Issues',
                'ordering': ('-priority', 'created_at'),
            },
        ),
    ]
