# Generated by Django 5.2.7 on 2025-10-03 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveSmallIntegerField(help_text='Score out of 100', verbose_name='Overall Score')),
                ('strengths_summary', models.TextField(blank=True, null=True, verbose_name='Strengths Summary')),
                ('weaknesses_summary', models.TextField(blank=True, null=True, verbose_name='Areas for Improvement')),
                ('is_auto_generated', models.BooleanField(default=True, help_text='Whether this analysis was generated automatically', verbose_name='Is Auto Generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_resumes', to=settings.AUTH_USER_MODEL, verbose_name='Analyzed By')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis', to='applications.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Highlighted Text')),
                ('highlight_type', models.CharField(choices=[('strength', 'Strength'), ('weakness', 'Weakness'), ('neutral', 'Neutral')], default='neutral', max_length=10, verbose_name='Highlight Type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('suggested_improvement', models.TextField(blank=True, null=True, verbose_name='Suggested Improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='resume_highlighter.resumeanalysis', verbose_name='Resume Analysis')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_highlights', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Resume Highlight',
                'verbose_name_plural': 'Resume Highlights',
                'ordering': ['-created_at'],
            },
        ),
    ]
