# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this saved search', max_length=255, verbose_name='search name')),
                ('search_type', models.CharField(choices=[('job', 'Job Search'), ('candidate', 'Candidate Search'), ('company', 'Company Search'), ('advanced_candidate', 'Advanced Candidate Search')], default='job', max_length=20, verbose_name='search type')),
                ('query', models.CharField(blank=True, help_text='Job title, keywords, or company name', max_length=500, null=True, verbose_name='search query')),
                ('location', models.JSONField(blank=True, help_text='Selected locations', null=True, verbose_name='locations')),
                ('experience', models.JSONField(blank=True, help_text='Selected experience levels', null=True, verbose_name='experience levels')),
                ('salary', models.JSONField(blank=True, help_text='Selected salary ranges', null=True, verbose_name='salary ranges')),
                ('job_type', models.JSONField(blank=True, help_text='Selected job types', null=True, verbose_name='job types')),
                ('skills', models.JSONField(blank=True, help_text='List of required skills', null=True, verbose_name='skills')),
                ('company', models.JSONField(blank=True, help_text='Selected companies', null=True, verbose_name='companies')),
                ('industry', models.JSONField(blank=True, help_text='Selected industries', null=True, verbose_name='industries')),
                ('department', models.JSONField(blank=True, help_text='Selected departments', null=True, verbose_name='departments')),
                ('role', models.JSONField(blank=True, help_text='Selected roles', null=True, verbose_name='roles')),
                ('education', models.JSONField(blank=True, help_text='Selected education levels', null=True, verbose_name='education levels')),
                ('gender', models.JSONField(blank=True, help_text='Selected genders', null=True, verbose_name='genders')),
                ('age', models.JSONField(blank=True, help_text='Selected age range', null=True, verbose_name='age range')),
                ('last_active', models.CharField(blank=True, help_text='Last active time period', max_length=50, null=True, verbose_name='last active')),
                ('notice_period', models.JSONField(blank=True, help_text='Selected notice periods', null=True, verbose_name='notice periods')),
                ('work_mode', models.JSONField(blank=True, help_text='Selected work modes', null=True, verbose_name='work modes')),
                ('job_change', models.BooleanField(blank=True, help_text='Is candidate open to job change', null=True, verbose_name='open to job change')),
                ('willing_to_relocate', models.BooleanField(blank=True, help_text='Is candidate willing to relocate', null=True, verbose_name='willing to relocate')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this saved search', verbose_name='is active')),
                ('email_alerts', models.BooleanField(default=False, help_text='Receive email notifications for new matches', verbose_name='email alerts')),
                ('alert_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (7, 'Weekly')], default=1, verbose_name='alert frequency')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True, verbose_name='last alert sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('total_results', models.PositiveIntegerField(default=0, verbose_name='total results')),
                ('new_since_last_alert', models.PositiveIntegerField(default=0, verbose_name='new since last alert')),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'ordering': ['-updated_at'],
            },
        ),
    ]
