# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IvrCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(help_text='Unique identifier from the telephony provider', max_length=100, unique=True, verbose_name='call SID')),
                ('from_number', models.CharField(help_text='The phone number that made the call', max_length=20, verbose_name='from number')),
                ('to_number', models.CharField(help_text='The phone number that received the call', max_length=20, verbose_name='to number')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer')], default='queued', max_length=20, verbose_name='call status')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Call duration in seconds', null=True, verbose_name='call duration')),
                ('recording_url', models.URLField(blank=True, help_text='URL to the call recording, if available', verbose_name='recording URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='Cost of the call in USD', max_digits=10, null=True, verbose_name='call price')),
                ('price_unit', models.CharField(default='USD', help_text='Currency for the call price', max_length=3, verbose_name='price unit')),
                ('provider_data', models.JSONField(blank=True, default=dict, help_text='Raw data from the telephony provider', verbose_name='provider data')),
                ('error_message', models.TextField(blank=True, help_text='Error details if the call failed', verbose_name='error message')),
            ],
            options={
                'verbose_name': 'IVR call log',
                'verbose_name_plural': 'IVR call logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IvrVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number to verify', max_length=20, verbose_name='phone number')),
                ('verification_code', models.CharField(help_text='The code sent for verification', max_length=10, verbose_name='verification code')),
                ('method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='call', max_length=20, verbose_name='verification method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='verification status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts made', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was successfully completed', null=True, verbose_name='verified at')),
                ('expires_at', models.DateTimeField(help_text='When this verification code expires', verbose_name='expires at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the device initiating verification', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the device/browser', verbose_name='user agent')),
                ('is_successful', models.BooleanField(default=False, help_text='Whether the verification was successful', verbose_name='is successful')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for verification failure, if any', verbose_name='failure reason')),
            ],
            options={
                'verbose_name': 'IVR verification',
                'verbose_name_plural': 'IVR verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
