# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivr_verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ivrverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_verifications', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='ivrcalllog',
            name='verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_log', to='ivr_verification.ivrverification', verbose_name='verification'),
        ),
        migrations.AddIndex(
            model_name='ivrverification',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='ivr_verific_user_id_0feda3_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrverification',
            index=models.Index(fields=['phone_number', 'verification_code'], name='ivr_verific_phone_n_e3f72b_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrcalllog',
            index=models.Index(fields=['call_sid'], name='ivr_verific_call_si_aa5fad_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrcalllog',
            index=models.Index(fields=['from_number'], name='ivr_verific_from_nu_272122_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrcalllog',
            index=models.Index(fields=['to_number'], name='ivr_verific_to_numb_96d241_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrcalllog',
            index=models.Index(fields=['status'], name='ivr_verific_status_21f982_idx'),
        ),
        migrations.AddIndex(
            model_name='ivrcalllog',
            index=models.Index(fields=['created_at'], name='ivr_verific_created_6f98f0_idx'),
        ),
    ]
