# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IvrCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Call SID')),
                ('parent_call_sid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Call SID')),
                ('from_number', models.CharField(max_length=20, verbose_name='From Number')),
                ('to_number', models.CharField(max_length=20, verbose_name='To Number')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10, verbose_name='Direction')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], default='initiated', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Recording URL')),
                ('current_menu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Menu')),
                ('digits_pressed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Digits Pressed')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'IVR Call',
                'verbose_name_plural': 'IVR Calls',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='IvrCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'IVR Call Log',
                'verbose_name_plural': 'IVR Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IvrMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('menu_type', models.CharField(choices=[('main', 'Main Menu'), ('submenu', 'Submenu'), ('action', 'Action')], default='main', max_length=10, verbose_name='Menu Type')),
                ('greeting_text', models.TextField(verbose_name='Greeting Text')),
                ('greeting_voice', models.FileField(blank=True, null=True, upload_to='ivr/greetings/', verbose_name='Greeting Voice')),
                ('invalid_choice_text', models.TextField(default='Invalid selection. Please try again.', verbose_name='Invalid Choice Text')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Max Retries')),
                ('timeout', models.PositiveSmallIntegerField(default=5, help_text='Time to wait for input before timeout', verbose_name='Timeout (seconds)')),
                ('finish_on_key', models.CharField(default='#', help_text='Key that ends input collection', max_length=1, verbose_name='Finish On Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Menu',
                'verbose_name_plural': 'IVR Menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IvrMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(help_text='Single digit (0-9, *, #) to trigger this option', max_length=1, verbose_name='Digit')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('action', models.CharField(choices=[('menu', 'Go to Menu'), ('call', 'Make Call'), ('hangup', 'Hang Up'), ('voicemail', 'Leave Voicemail'), ('callback', 'Request Callback')], default='menu', max_length=20, verbose_name='Action')),
                ('phone_number', models.CharField(blank=True, help_text='Number to call for call/callback actions', max_length=20, null=True, verbose_name='Phone Number')),
                ('confirmation_text', models.TextField(blank=True, verbose_name='Confirmation Text')),
                ('confirmation_voice', models.FileField(blank=True, null=True, upload_to='ivr/confirmations/', verbose_name='Confirmation Voice')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'IVR Menu Option',
                'verbose_name_plural': 'IVR Menu Options',
                'ordering': ['order', 'digit'],
            },
        ),
    ]
