# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ivrcall',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr_calls', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ivrcalllog',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ivr.ivrcall', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='ivrmenuoption',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ivr.ivrmenu', verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='ivrmenuoption',
            name='target_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by', to='ivr.ivrmenu', verbose_name='Target Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='ivrmenuoption',
            unique_together={('menu', 'digit')},
        ),
    ]
