# Generated by Django 5.2.7 on 2025-10-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0002_fix_duplicate_profiles'),
    ]

    operations = [
    ]
