# Generated by Django 5.2.7 on 2025-10-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Folder Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Folder')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='FolderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_folder_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_profiles', to='folders.folder', verbose_name='Folder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_folders', to='profile.userprofile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Folder Profile',
                'verbose_name_plural': 'Folder Profiles',
                'ordering': ['-added_at'],
                'unique_together': {('folder', 'profile')},
            },
        ),
    ]
