# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.JSONField(verbose_name='Search Parameters')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Results Count')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Is Saved')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword')),
                ('location', models.JSONField(blank=True, default=list, verbose_name='Locations')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='Experience Range')),
                ('salary', models.JSONField(blank=True, default=list, verbose_name='Salary Range')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Skills')),
                ('job_type', models.JSONField(blank=True, default=list, verbose_name='Job Type')),
                ('company', models.JSONField(blank=True, default=list, verbose_name='Companies')),
                ('industry', models.JSONField(blank=True, default=list, verbose_name='Industries')),
                ('department', models.JSONField(blank=True, default=list, verbose_name='Departments')),
                ('role', models.JSONField(blank=True, default=list, verbose_name='Roles')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Education')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender')),
                ('notice_period', models.JSONField(blank=True, default=list, verbose_name='Notice Period')),
                ('work_mode', models.JSONField(blank=True, default=list, verbose_name='Work Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Candidate Search Query',
                'verbose_name_plural': 'Candidate Search Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Search Name')),
                ('search_parameters', models.JSONField(verbose_name='Search Parameters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('skills', 'Skills'), ('location', 'Location'), ('experience', 'Experience'), ('salary', 'Salary'), ('job_type', 'Job Type'), ('company', 'Company'), ('industry', 'Industry'), ('department', 'Department'), ('role', 'Role'), ('education', 'Education'), ('gender', 'Gender'), ('notice_period', 'Notice Period'), ('work_mode', 'Work Mode')], max_length=50, verbose_name='Filter Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Search Filter Option',
                'verbose_name_plural': 'Search Filter Options',
                'ordering': ['filter_type', 'display_order', 'name'],
            },
        ),
    ]
