# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmediateAvailableProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_immediately_available', models.BooleanField(default=False, help_text='Whether the candidate is immediately available for work', verbose_name='Is Immediately Available')),
                ('available_from', models.DateField(blank=True, help_text='Date from which the candidate is available', null=True, verbose_name='Available From')),
                ('notice_period', models.PositiveIntegerField(default=0, help_text='Notice period in days', verbose_name='Notice Period (Days)')),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, help_text='Current CTC in Lakhs Per Annum', max_digits=10, null=True, verbose_name='Current CTC (LPA)')),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, help_text='Expected CTC in Lakhs Per Annum', max_digits=10, null=True, verbose_name='Expected CTC (LPA)')),
                ('preferred_locations', models.JSONField(blank=True, default=list, help_text='List of preferred work locations', verbose_name='Preferred Locations')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills the candidate possesses', verbose_name='Skills')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('experience_months', models.PositiveIntegerField(default=0, verbose_name='Months of Experience')),
                ('current_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Company')),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Designation')),
                ('last_working_day', models.DateField(blank=True, null=True, verbose_name='Last Working Day')),
                ('is_serving_notice', models.BooleanField(default=False, verbose_name='Is Serving Notice Period')),
                ('notice_period_negotiable', models.BooleanField(default=False, verbose_name='Notice Period Negotiable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Immediate Available Profile',
                'verbose_name_plural': 'Immediate Available Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
