# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IvrDashboardFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Filter Name')),
                ('filter_type', models.CharField(choices=[('date_range', 'Date Range'), ('call_status', 'Call Status'), ('call_direction', 'Call Direction'), ('phone_number', 'Phone Number'), ('ivr_menu', 'IVR Menu'), ('custom', 'Custom')], max_length=50, verbose_name='Filter Type')),
                ('is_global', models.BooleanField(default=False, help_text='Apply this filter to all dashboard panels', verbose_name='Apply Globally')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default filter for the dashboard', verbose_name='Default Filter')),
                ('filter_values', models.JSONField(blank=True, default=dict, verbose_name='Filter Values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Dashboard Filter',
                'verbose_name_plural': 'IVR Dashboard Filters',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IvrDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Layout Name')),
                ('layout_type', models.CharField(choices=[('default', 'Default'), ('analyst', 'Analyst'), ('manager', 'Manager'), ('executive', 'Executive'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Layout Type')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default layout for the dashboard', verbose_name='Default Layout')),
                ('layout_data', models.JSONField(blank=True, default=dict, verbose_name='Layout Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Dashboard Layout',
                'verbose_name_plural': 'IVR Dashboard Layouts',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IvrDashboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dashboard panel', max_length=100, verbose_name='Panel Name')),
                ('panel_type', models.CharField(choices=[('call_metrics', 'Call Metrics'), ('call_volume', 'Call Volume'), ('call_duration', 'Call Duration'), ('call_status', 'Call Status Distribution'), ('top_callers', 'Top Callers'), ('recent_calls', 'Recent Calls'), ('ivr_performance', 'IVR Performance'), ('custom', 'Custom')], max_length=50, verbose_name='Panel Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('row', models.PositiveSmallIntegerField(default=0, verbose_name='Row')),
                ('col', models.PositiveSmallIntegerField(default=0, verbose_name='Column')),
                ('size_x', models.PositiveSmallIntegerField(default=4, verbose_name='Width')),
                ('size_y', models.PositiveSmallIntegerField(default=4, verbose_name='Height')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('refresh_interval', models.PositiveIntegerField(default=60, help_text='How often to refresh the panel data (in seconds). 0 = no refresh', verbose_name='Refresh Interval (seconds)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Dashboard Panel',
                'verbose_name_plural': 'IVR Dashboard Panels',
                'ordering': ['user', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IvrDashboardSharedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='View Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, help_text='Make this view available to all users', verbose_name='Is Public')),
                ('view_data', models.JSONField(blank=True, default=dict, verbose_name='View Data')),
                ('share_token', models.UUIDField(blank=True, help_text='Unique token for public sharing of this view', null=True, unique=True, verbose_name='Share Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Dashboard Shared View',
                'verbose_name_plural': 'IVR Dashboard Shared Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IvrDashboardUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=20, verbose_name='Theme')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for important dashboard events', verbose_name='Email Notifications')),
                ('auto_refresh', models.BooleanField(default=True, help_text='Automatically refresh dashboard data', verbose_name='Auto Refresh')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='How often to refresh dashboard data (in seconds)', verbose_name='Refresh Interval (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IVR Dashboard User Settings',
                'verbose_name_plural': 'IVR Dashboard User Settings',
            },
        ),
    ]
