# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivr_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ivrdashboardfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_dashboard_filters', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ivrdashboardlayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_dashboard_layouts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ivrdashboardpanel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_dashboard_panels', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ivrdashboardsharedview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ivr_dashboard_views', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ivrdashboardsharedview',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='accessible_ivr_dashboard_views', to=settings.AUTH_USER_MODEL, verbose_name='Shared With'),
        ),
        migrations.AddField(
            model_name='ivrdashboardusersettings',
            name='default_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='ivr_dashboard.ivrdashboardlayout', verbose_name='Default Layout'),
        ),
        migrations.AddField(
            model_name='ivrdashboardusersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='ivrdashboardfilter',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ivrdashboardlayout',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ivrdashboardpanel',
            unique_together={('user', 'panel_type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='ivrdashboardsharedview',
            unique_together={('created_by', 'name')},
        ),
    ]
