# Generated by Django 5.2.7 on 2025-10-03 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Setting Name')),
                ('value', models.JSONField(help_text='JSON-encoded setting value', verbose_name='Setting Value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Resume Score Setting',
                'verbose_name_plural': 'Resume Score Settings',
            },
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(max_length=500, upload_to='resume_scores/%Y/%m/%d/', verbose_name='Resume File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(help_text='Size of the uploaded file in bytes', verbose_name='File Size (bytes)')),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, help_text='Overall resume score (0-100)', null=True, verbose_name='Overall Score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('ats_score', models.PositiveSmallIntegerField(blank=True, help_text='Score based on ATS compatibility (0-100)', null=True, verbose_name='ATS Score')),
                ('content_score', models.PositiveSmallIntegerField(blank=True, help_text='Score based on content quality (0-100)', null=True, verbose_name='Content Score')),
                ('design_score', models.PositiveSmallIntegerField(blank=True, help_text='Score based on design and formatting (0-100)', null=True, verbose_name='Design Score')),
                ('strengths', models.JSONField(default=list, help_text='List of strengths found in the resume', verbose_name='Strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of areas that need improvement', verbose_name='Areas for Improvement')),
                ('keyword_matches', models.JSONField(default=dict, help_text='Keywords found and their relevance', verbose_name='Keyword Matches')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Job Title')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_scores', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume Score',
                'verbose_name_plural': 'Resume Scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('content', 'Content'), ('formatting', 'Formatting'), ('keywords', 'Keywords'), ('length', 'Length'), ('design', 'Design')], default='content', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the improvement', verbose_name='Description')),
                ('example_before', models.TextField(blank=True, help_text='Example of current content (before improvement)', null=True, verbose_name='Example Before')),
                ('example_after', models.TextField(blank=True, help_text='Example of improved content', null=True, verbose_name='Example After')),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the improvement has been applied', verbose_name='Is Applied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resume_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='resume_scorer.resumescore', verbose_name='Resume Score')),
            ],
            options={
                'verbose_name': 'Score Improvement',
                'verbose_name_plural': 'Score Improvements',
                'ordering': ['priority', 'category'],
            },
        ),
    ]
