# Generated by Django 5.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedIvrResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Resource Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('resource_type', models.CharField(choices=[('audio', 'Audio File'), ('prompt', 'Voice Prompt'), ('script', 'IVR Script'), ('greeting', 'Greeting Message'), ('other', 'Other')], default='audio', max_length=20, verbose_name='Resource Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='ivr/shared/resources/', verbose_name='File')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('language', models.CharField(default='en', help_text='ISO 639-1 language code', max_length=10, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shared IVR Resource',
                'verbose_name_plural': 'Shared IVR Resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedIvrTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('greeting', 'Greeting'), ('menu', 'Menu'), ('verification', 'Verification'), ('survey', 'Survey'), ('appointment', 'Appointment'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Template Type')),
                ('content', models.JSONField(default=dict, verbose_name='Template Content')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_public', models.BooleanField(default=False, help_text='If checked, this template can be used by all users', verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shared IVR Template',
                'verbose_name_plural': 'Shared IVR Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedIvrUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('resource', 'Resource'), ('template', 'Template')], max_length=10, verbose_name='Resource Type')),
                ('resource_id', models.PositiveIntegerField(verbose_name='Resource ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('used', 'Used'), ('exported', 'Exported'), ('imported', 'Imported')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'IVR Usage Log',
                'verbose_name_plural': 'IVR Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
