# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivr_shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedivrresource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ivr_resources', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='sharedivrtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ivr_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='sharedivrtemplate',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='templates', to='ivr_shared.sharedivrresource', verbose_name='Resources'),
        ),
        migrations.AddField(
            model_name='sharedivrusagelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='sharedivrresource',
            index=models.Index(fields=['resource_type'], name='ivr_shared__resourc_1ddfab_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrresource',
            index=models.Index(fields=['language'], name='ivr_shared__languag_4a805a_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrresource',
            index=models.Index(fields=['is_active'], name='ivr_shared__is_acti_fed7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrtemplate',
            index=models.Index(fields=['template_type'], name='ivr_shared__templat_86e666_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrtemplate',
            index=models.Index(fields=['is_active'], name='ivr_shared__is_acti_56cdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrtemplate',
            index=models.Index(fields=['is_public'], name='ivr_shared__is_publ_c02ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrusagelog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='ivr_shared__resourc_5b3338_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrusagelog',
            index=models.Index(fields=['action'], name='ivr_shared__action_e4bef0_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedivrusagelog',
            index=models.Index(fields=['timestamp'], name='ivr_shared__timesta_28856d_idx'),
        ),
    ]
