# Generated by Django 5.2.7 on 2025-10-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('current_company', models.CharField(blank=True, max_length=255, verbose_name='Current Company')),
                ('designation', models.CharField(blank=True, max_length=255, verbose_name='Designation')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('experience_months', models.PositiveIntegerField(default=0, verbose_name='Months of Experience')),
                ('highest_qualification', models.CharField(blank=True, max_length=255, verbose_name='Highest Qualification')),
                ('institute', models.CharField(blank=True, max_length=255, verbose_name='Institute')),
                ('year_of_passing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Passing')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Skills')),
                ('preferred_locations', models.JSONField(blank=True, default=list, verbose_name='Preferred Locations')),
                ('job_roles', models.JSONField(blank=True, default=list, verbose_name='Preferred Job Roles')),
                ('profile_completion', models.PositiveIntegerField(default=0, verbose_name='Profile Completion %')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='Profile Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
