# Generated by Django 5.2.7 on 2025-10-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Profile', 'verbose_name_plural': 'Candidate Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('profile_completion', models.PositiveIntegerField(default=0, verbose_name='Profile Completion %')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='Profile Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_website', models.URLField(blank=True, verbose_name='Company Website')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('company_description', models.TextField(blank=True, verbose_name='Company Description')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Person Name')),
                ('contact_person_designation', models.CharField(blank=True, max_length=255, verbose_name='Designation')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Profile')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5000+', '5000+ employees')], max_length=20, verbose_name='Company Size')),
                ('industry', models.CharField(blank=True, max_length=255, verbose_name='Industry')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
