# Generated by Django 5.2.7 on 2025-10-03 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('job', 'Job Search'), ('candidate', 'Candidate Search'), ('company', 'Company Search')], max_length=20, verbose_name='search type')),
                ('query', models.CharField(blank=True, max_length=500, null=True, verbose_name='search query')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='search filters')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'recent search',
                'verbose_name_plural': 'recent searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'search_type', '-created_at'], name='recent_sear_user_id_41bde8_idx')],
            },
        ),
    ]
