# Generated by Django 5.2.7 on 2025-10-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_type', 'created_at'], name='search_sear_search__481565_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', 'created_at'], name='search_sear_user_id_feedf5_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query', 'location'], name='search_sear_query_448ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['company'], name='search_sear_company_94815a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at', 'search_type'], name='search_sear_created_769563_idx'),
        ),
    ]
