# Generated by Django 5.2.7 on 2025-10-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offer', 'Offer Sent'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('website', 'Website'), ('email', 'Email'), ('api', 'API'), ('manual', 'Manual Entry')], default='website', max_length=20, verbose_name='Source')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Resume')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Is Rejected')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_applications_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_notes_authored', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_notes', to='job_posting.jobapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Job Posting Application Note',
                'verbose_name_plural': 'Job Posting Application Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefits')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Remote Position')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20, verbose_name='Job Type')),
                ('experience_level', models.CharField(choices=[('internship', 'Internship'), ('entry', 'Entry Level'), ('associate', 'Associate'), ('mid_senior', 'Mid-Senior Level'), ('director', 'Director'), ('executive', 'Executive')], default='mid_senior', max_length=20, verbose_name='Experience Level')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('salary_currency', models.CharField(default='USD', max_length=3, verbose_name='Salary Currency')),
                ('salary_display', models.CharField(blank=True, help_text='E.g., "$100,000 - $150,000 a year"', max_length=255, verbose_name='Salary Display')),
                ('application_url', models.URLField(blank=True, verbose_name='Application URL')),
                ('application_email', models.EmailField(blank=True, max_length=254, verbose_name='Application Email')),
                ('application_instructions', models.TextField(blank=True, verbose_name='Application Instructions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Job')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='Applications Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.company', verbose_name='Company')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings_posted', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_applications', to='job_posting.jobposting', verbose_name='Job Posting'),
        ),
    ]
