# Generated by Django 5.2.7 on 2025-10-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('profile', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'user__user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profile.userprofile'),
        ),
    ]
