# Generated by Django 5.2.7 on 2025-10-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_resume', models.FileField(max_length=500, upload_to='resumes/enhancements/original/%Y/%m/%d/', verbose_name='Original Resume')),
                ('enhanced_resume', models.FileField(blank=True, max_length=500, null=True, upload_to='resumes/enhancements/enhanced/%Y/%m/%d/', verbose_name='Enhanced Resume')),
                ('enhancement_type', models.CharField(choices=[('entry_level', 'Entry Level'), ('ats_optimization', 'ATS Optimization'), ('design_enhancement', 'Design Enhancement'), ('content_improvement', 'Content Improvement')], default='entry_level', max_length=50, verbose_name='Enhancement Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('score_before', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score Before')),
                ('score_after', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score After')),
                ('improvements', models.JSONField(default=list, help_text='List of improvements made to the resume', verbose_name='Improvements')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_enhancements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume Enhancement',
                'verbose_name_plural': 'Resume Enhancements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEnhancementFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True, verbose_name='Rating')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('would_recommend', models.BooleanField(blank=True, null=True, verbose_name='Would Recommend')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('enhancement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='resume_enhancer.resumeenhancement', verbose_name='Enhancement')),
            ],
            options={
                'verbose_name': 'Resume Enhancement Feedback',
                'verbose_name_plural': 'Resume Enhancement Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
